(import (chezpp))


(mat xxhash32

     (error? (xxhash32-fixnum #f))
     (error? (xxhash32-flonum #f))
     (error? (xxhash32-ratnum #f))
     (error? (xxhash32-cflonum #f))
     (error? (xxhash32-bool 0))
     (error? (xxhash32-char 0))
     (error? (xxhash32-string 0))
     (error? (xxhash32-fxvector 0))
     (error? (xxhash32-flvector 0))
     (error? (xxhash32-bytevector 0))
     (error? (xxhash32-file 0))

     ;; invalid salt
     (error? (xxhash32-fixnum 1 (ash (most-positive-fixnum) 2)))
     (error? (xxhash32-flonum 1.0 (ash (most-positive-fixnum) 2)))
     (error? (xxhash32-ratnum 1/2 (ash (most-positive-fixnum) 2)))
     (error? (xxhash32-cflonum 1.2+2.5i (ash (most-positive-fixnum) 2)))
     (error? (xxhash32-bool #t (ash (most-positive-fixnum) 2)))
     (error? (xxhash32-char #\A (ash (most-positive-fixnum) 2)))
     (error? (xxhash32-string "hello" (ash (most-positive-fixnum) 2)))
     (error? (xxhash32-fxvector (fxvector 1) (ash (most-positive-fixnum) 2)))
     (error? (xxhash32-flvector (flvector 1.5) (ash (most-positive-fixnum) 2)))
     (error? (xxhash32-bytevector (bytevector 1) (ash (most-positive-fixnum) 2)))
     (error? (xxhash32-file "/etc/fstab" (ash (most-positive-fixnum) 2)))

     ;; salt
     (not (= (xxhash32-fixnum 1)
             (xxhash32-fixnum 1 42)))
     (not (= (xxhash32-flonum 1.0)
             (xxhash32-flonum 1.0 42)))
     (not (= (xxhash32-ratnum 1/2)
             (xxhash32-ratnum 1/2 42)))
     (not (= (xxhash32-cflonum 1.2+2.5i)
             (xxhash32-cflonum 1.2+2.5i 42)))
     (not (= (xxhash32-bool #t)
             (xxhash32-bool #t 42)))
     (not (= (xxhash32-char #\A)
             (xxhash32-char #\A 42)))
     (not (= (xxhash32-string "hello")
             (xxhash32-string "hello" 42)))
     (not (= (xxhash32-fxvector (fxvector 1))
             (xxhash32-fxvector (fxvector 1) 42)))
     (not (= (xxhash32-flvector (flvector 1.5))
             (xxhash32-flvector (flvector 1.5) 42)))
     (not (= (xxhash32-bytevector (bytevector 1))
             (xxhash32-bytevector (bytevector 1) 42)))
     (not (= (xxhash32-file "/etc/fstab")
             (xxhash32-file "/etc/fstab" 42)))

     ;; invalid ranges
     (error? (xxhash32-string "hello" 42 -1 3))
     (error? (xxhash32-fxvector (fxvector 1 2 3 4 5) 42 -1 3))
     (error? (xxhash32-flvector (flvector 1.5 2.5 3.5 4.5 5.5) 42 -1 3))
     (error? (xxhash32-bytevector (bytevector 1 2 3 4 5) 42 -1 3))
     (error? (xxhash32-file "/etc/fstab" 42 -1 3))

     (error? (xxhash32-string "hello" 42 1 33))
     (error? (xxhash32-fxvector (fxvector 1 2 3 4 5) 42 1 33))
     (error? (xxhash32-flvector (flvector 1.5 2.5 3.5 4.5 5.5) 42 1 33))
     (error? (xxhash32-bytevector (bytevector 1 2 3 4 5) 42 1 33))
     (error? (xxhash32-file "/etc/fstab" 42 1 (ash 2 32)))

     ;; ranges
     (not (= (xxhash32-string "hello")
             (xxhash32-string "hello" 42 1 3)))
     (not (= (xxhash32-fxvector (fxvector 1 2 3 4 5))
             (xxhash32-fxvector (fxvector 1 2 3 4 5) 42 1 3)))
     (not (= (xxhash32-flvector (flvector 1.5 2.5 3.5 4.5 5.5))
             (xxhash32-flvector (flvector 1.5 2.5 3.5 4.5 5.5) 42 1 3)))
     (not (= (xxhash32-bytevector (bytevector 1 2 3 4 5))
             (xxhash32-bytevector (bytevector 1 2 3 4 5) 42 1 3)))
     (not (= (xxhash32-file "/etc/fstab")
             (xxhash32-file "/etc/fstab" 42 1 3)))

     ;; tag
     (not (= (xxhash32-bool #t)
             (xxhash32-fixnum 1)))
     (not (= (xxhash32-bool #f)
             (xxhash32-fixnum 0)))
     (not (= (xxhash32-char #\A)
             (xxhash32-fixnum 65)))
     (not (= (xxhash32-fxvector (fxvector 1))
             (xxhash32-bytevector (bytevector 1))))
     (not (= (xxhash32-ratnum 1/2)
             (xxhash32-fxvector (fxvector 1 2))))
     (not (= (xxhash32-cflonum 1.2+2.5i)
             (xxhash32-flvector (flvector 1.2 2.5))))

     )


(mat xxhash64

     (error? (xxhash64-fixnum #f))
     (error? (xxhash64-flonum #f))
     (error? (xxhash64-ratnum #f))
     (error? (xxhash64-cflonum #f))
     (error? (xxhash64-bool 0))
     (error? (xxhash64-char 0))
     (error? (xxhash64-string 0))
     (error? (xxhash64-fxvector 0))
     (error? (xxhash64-flvector 0))
     (error? (xxhash64-bytevector 0))
     (error? (xxhash64-file 0))

     ;; invalid salt
     (error? (xxhash64-fixnum 1 (ash (most-positive-fixnum) 2)))
     (error? (xxhash64-flonum 1.0 (ash (most-positive-fixnum) 2)))
     (error? (xxhash64-ratnum 1/2 (ash (most-positive-fixnum) 2)))
     (error? (xxhash64-cflonum 1.2+2.5i (ash (most-positive-fixnum) 2)))
     (error? (xxhash64-bool #t (ash (most-positive-fixnum) 2)))
     (error? (xxhash64-char #\A (ash (most-positive-fixnum) 2)))
     (error? (xxhash64-string "hello" (ash (most-positive-fixnum) 2)))
     (error? (xxhash64-fxvector (fxvector 1) (ash (most-positive-fixnum) 2)))
     (error? (xxhash64-flvector (flvector 1.5) (ash (most-positive-fixnum) 2)))
     (error? (xxhash64-bytevector (bytevector 1) (ash (most-positive-fixnum) 2)))
     (error? (xxhash64-file "/etc/fstab" (ash (most-positive-fixnum) 2)))

     ;; salt
     (not (= (xxhash64-fixnum 1)
             (xxhash64-fixnum 1 42)))
     (not (= (xxhash64-flonum 1.0)
             (xxhash64-flonum 1.0 42)))
     (not (= (xxhash64-ratnum 1/2)
             (xxhash64-ratnum 1/2 42)))
     (not (= (xxhash64-cflonum 1.2+2.5i)
             (xxhash64-cflonum 1.2+2.5i 42)))
     (not (= (xxhash64-bool #t)
             (xxhash64-bool #t 42)))
     (not (= (xxhash64-char #\A)
             (xxhash64-char #\A 42)))
     (not (= (xxhash64-string "hello")
             (xxhash64-string "hello" 42)))
     (not (= (xxhash64-fxvector (fxvector 1))
             (xxhash64-fxvector (fxvector 1) 42)))
     (not (= (xxhash64-flvector (flvector 1.5))
             (xxhash64-flvector (flvector 1.5) 42)))
     (not (= (xxhash64-bytevector (bytevector 1))
             (xxhash64-bytevector (bytevector 1) 42)))
     (not (= (xxhash64-file "/etc/fstab")
             (xxhash64-file "/etc/fstab" 42)))

     ;; invalid ranges
     (error? (xxhash64-string "hello" 42 -1 3))
     (error? (xxhash64-fxvector (fxvector 1 2 3 4 5) 42 -1 3))
     (error? (xxhash64-flvector (flvector 1.5 2.5 3.5 4.5 5.5) 42 -1 3))
     (error? (xxhash64-bytevector (bytevector 1 2 3 4 5) 42 -1 3))
     (error? (xxhash64-file "/etc/fstab" 42 -1 3))

     (error? (xxhash64-string "hello" 42 1 33))
     (error? (xxhash64-fxvector (fxvector 1 2 3 4 5) 42 1 33))
     (error? (xxhash64-flvector (flvector 1.5 2.5 3.5 4.5 5.5) 42 1 33))
     (error? (xxhash64-bytevector (bytevector 1 2 3 4 5) 42 1 33))
     (error? (xxhash64-file "/etc/fstab" 42 1 (ash 2 32)))

     ;; ranges
     (not (= (xxhash64-string "hello")
             (xxhash64-string "hello" 42 1 3)))
     (not (= (xxhash64-fxvector (fxvector 1 2 3 4 5))
             (xxhash64-fxvector (fxvector 1 2 3 4 5) 42 1 3)))
     (not (= (xxhash64-flvector (flvector 1.5 2.5 3.5 4.5 5.5))
             (xxhash64-flvector (flvector 1.5 2.5 3.5 4.5 5.5) 42 1 3)))
     (not (= (xxhash64-bytevector (bytevector 1 2 3 4 5))
             (xxhash64-bytevector (bytevector 1 2 3 4 5) 42 1 3)))
     (not (= (xxhash64-file "/etc/fstab")
             (xxhash64-file "/etc/fstab" 42 1 3)))

     ;; tag
     (not (= (xxhash64-bool #t)
             (xxhash64-fixnum 1)))
     (not (= (xxhash64-bool #f)
             (xxhash64-fixnum 0)))
     (not (= (xxhash64-char #\A)
             (xxhash64-fixnum 65)))
     (not (= (xxhash64-fxvector (fxvector 1))
             (xxhash64-bytevector (bytevector 1))))
     (not (= (xxhash64-ratnum 1/2)
             (xxhash64-fxvector (fxvector 1 2))))
     (not (= (xxhash64-cflonum 1.2+2.5i)
             (xxhash64-flvector (flvector 1.2 2.5))))

     )


(mat xxhash3-64

     (error? (xxhash3-64-fixnum #f))
     (error? (xxhash3-64-flonum #f))
     (error? (xxhash3-64-ratnum #f))
     (error? (xxhash3-64-cflonum #f))
     (error? (xxhash3-64-bool 0))
     (error? (xxhash3-64-char 0))
     (error? (xxhash3-64-string 0))
     (error? (xxhash3-64-fxvector 0))
     (error? (xxhash3-64-flvector 0))
     (error? (xxhash3-64-bytevector 0))
     (error? (xxhash3-64-file 0))

     ;; invalid salt
     (error? (xxhash3-64-fixnum 1 (ash (most-positive-fixnum) 2)))
     (error? (xxhash3-64-flonum 1.0 (ash (most-positive-fixnum) 2)))
     (error? (xxhash3-64-ratnum 1/2 (ash (most-positive-fixnum) 2)))
     (error? (xxhash3-64-cflonum 1.2+2.5i (ash (most-positive-fixnum) 2)))
     (error? (xxhash3-64-bool #t (ash (most-positive-fixnum) 2)))
     (error? (xxhash3-64-char #\A (ash (most-positive-fixnum) 2)))
     (error? (xxhash3-64-string "hello" (ash (most-positive-fixnum) 2)))
     (error? (xxhash3-64-fxvector (fxvector 1) (ash (most-positive-fixnum) 2)))
     (error? (xxhash3-64-flvector (flvector 1.5) (ash (most-positive-fixnum) 2)))
     (error? (xxhash3-64-bytevector (bytevector 1) (ash (most-positive-fixnum) 2)))
     (error? (xxhash3-64-file "/etc/fstab" (ash (most-positive-fixnum) 2)))

     ;; salt
     (not (= (xxhash3-64-fixnum 1)
             (xxhash3-64-fixnum 1 42)))
     (not (= (xxhash3-64-flonum 1.0)
             (xxhash3-64-flonum 1.0 42)))
     (not (= (xxhash3-64-ratnum 1/2)
             (xxhash3-64-ratnum 1/2 42)))
     (not (= (xxhash3-64-cflonum 1.2+2.5i)
             (xxhash3-64-cflonum 1.2+2.5i 42)))
     (not (= (xxhash3-64-bool #t)
             (xxhash3-64-bool #t 42)))
     (not (= (xxhash3-64-char #\A)
             (xxhash3-64-char #\A 42)))
     (not (= (xxhash3-64-string "hello")
             (xxhash3-64-string "hello" 42)))
     (not (= (xxhash3-64-fxvector (fxvector 1))
             (xxhash3-64-fxvector (fxvector 1) 42)))
     (not (= (xxhash3-64-flvector (flvector 1.5))
             (xxhash3-64-flvector (flvector 1.5) 42)))
     (not (= (xxhash3-64-bytevector (bytevector 1))
             (xxhash3-64-bytevector (bytevector 1) 42)))
     (not (= (xxhash3-64-file "/etc/fstab")
             (xxhash3-64-file "/etc/fstab" 42)))

     ;; invalid ranges
     (error? (xxhash3-64-string "hello" 42 -1 3))
     (error? (xxhash3-64-fxvector (fxvector 1 2 3 4 5) 42 -1 3))
     (error? (xxhash3-64-flvector (flvector 1.5 2.5 3.5 4.5 5.5) 42 -1 3))
     (error? (xxhash3-64-bytevector (bytevector 1 2 3 4 5) 42 -1 3))
     (error? (xxhash3-64-file "/etc/fstab" 42 -1 3))

     (error? (xxhash3-64-string "hello" 42 1 33))
     (error? (xxhash3-64-fxvector (fxvector 1 2 3 4 5) 42 1 33))
     (error? (xxhash3-64-flvector (flvector 1.5 2.5 3.5 4.5 5.5) 42 1 33))
     (error? (xxhash3-64-bytevector (bytevector 1 2 3 4 5) 42 1 33))
     (error? (xxhash3-64-file "/etc/fstab" 42 1 (ash 2 32)))

     ;; ranges
     (not (= (xxhash3-64-string "hello")
             (xxhash3-64-string "hello" 42 1 3)))
     (not (= (xxhash3-64-fxvector (fxvector 1 2 3 4 5))
             (xxhash3-64-fxvector (fxvector 1 2 3 4 5) 42 1 3)))
     (not (= (xxhash3-64-flvector (flvector 1.5 2.5 3.5 4.5 5.5))
             (xxhash3-64-flvector (flvector 1.5 2.5 3.5 4.5 5.5) 42 1 3)))
     (not (= (xxhash3-64-bytevector (bytevector 1 2 3 4 5))
             (xxhash3-64-bytevector (bytevector 1 2 3 4 5) 42 1 3)))
     (not (= (xxhash3-64-file "/etc/fstab")
             (xxhash3-64-file "/etc/fstab" 42 1 3)))

     ;; tag
     (not (= (xxhash3-64-bool #t)
             (xxhash3-64-fixnum 1)))
     (not (= (xxhash3-64-bool #f)
             (xxhash3-64-fixnum 0)))
     (not (= (xxhash3-64-char #\A)
             (xxhash3-64-fixnum 65)))
     (not (= (xxhash3-64-fxvector (fxvector 1))
             (xxhash3-64-bytevector (bytevector 1))))
     (not (= (xxhash3-64-ratnum 1/2)
             (xxhash3-64-fxvector (fxvector 1 2))))
     (not (= (xxhash3-64-cflonum 1.2+2.5i)
             (xxhash3-64-flvector (flvector 1.2 2.5))))

     )


(mat hasher

     (error? (make-hasher 'bla))

     (error? (let ([h (make-hasher 'xxhash32)])
               (hasher-update-fixnum! h 1)
               (hasher-finalize! h)
               (hasher-update-fixnum! h 1)))

     (let ([h1 (make-hasher 'xxhash32)]
           [h2 (make-hasher 'xxhash32 42)])
       (assert (hasher? h1)) (assert (hasher? h2))

       (hasher-update-fixnum! h2 1)
       (hasher-update-flonum! h1 1.5) (hasher-update-flonum! h2 1.5)
       (hasher-update-ratnum! h1 1/2) (hasher-update-ratnum! h2 1/2)
       (hasher-update-cflonum! h1 1.5+2.5i) (hasher-update-cflonum! h2 1.5+2.5i)
       (hasher-update-bool! h1 #f) (hasher-update-bool! h2 #f)
       (hasher-update-char! h1 #\A) (hasher-update-char! h2 #\A)
       (hasher-update-string! h1 "hello") (hasher-update-string! h2 "hello")
       (hasher-update-fxvector! h1 (fxvector 1 2 3)) (hasher-update-fxvector! h2 (fxvector 1 2 3))
       (hasher-update-bytevector! h1 (bytevector 1 2 3)) (hasher-update-bytevector! h2 (bytevector 1 2 3))
       (hasher-update-flvector! h1 (flvector 1.1 2.2 3.3)) (hasher-update-flvector! h2 (flvector 1.1 2.2 3.3))

       (not (= (hasher-finalize! h1) (hasher-finalize! h2)))
       )

     (let ([h1 (make-hasher 'xxhash64)]
           [h2 (make-hasher 'xxhash64 42)])
       (assert (hasher? h1)) (assert (hasher? h2))

       (hasher-update-fixnum! h1 1) (hasher-update-fixnum! h2 1)
       (hasher-update-flonum! h1 1.5) (hasher-update-flonum! h2 1.5)
       (hasher-update-ratnum! h1 1/2) (hasher-update-ratnum! h2 1/2)
       (hasher-update-cflonum! h1 1.5+2.5i) (hasher-update-cflonum! h2 1.5+2.5i)
       (hasher-update-bool! h1 #f) (hasher-update-bool! h2 #f)
       (hasher-update-char! h1 #\A) (hasher-update-char! h2 #\A)
       (hasher-update-string! h1 "hello") (hasher-update-string! h2 "hello")
       (hasher-update-fxvector! h1 (fxvector 1 2 3)) (hasher-update-fxvector! h2 (fxvector 1 2 3))
       (hasher-update-bytevector! h1 (bytevector 1 2 3)) (hasher-update-bytevector! h2 (bytevector 1 2 3))
       (hasher-update-flvector! h1 (flvector 1.1 2.2 3.3)) (hasher-update-flvector! h2 (flvector 1.1 2.2 3.3))

       (not (= (hasher-finalize! h1) (hasher-finalize! h2)))
       )

     (let ([h1 (make-hasher 'xxhash3-64)]
           [h2 (make-hasher 'xxhash3-64 42)])
       (assert (hasher? h1)) (assert (hasher? h2))

       (hasher-update-fixnum! h1 1) (hasher-update-fixnum! h2 1)
       (hasher-update-flonum! h1 1.5) (hasher-update-flonum! h2 1.5)
       (hasher-update-ratnum! h1 1/2) (hasher-update-ratnum! h2 1/2)
       (hasher-update-cflonum! h1 1.5+2.5i) (hasher-update-cflonum! h2 1.5+2.5i)
       (hasher-update-bool! h1 #f) (hasher-update-bool! h2 #f)
       (hasher-update-char! h1 #\A) (hasher-update-char! h2 #\A)
       (hasher-update-string! h1 "hello") (hasher-update-string! h2 "hello")
       (hasher-update-fxvector! h1 (fxvector 1 2 3)) (hasher-update-fxvector! h2 (fxvector 1 2 3))
       (hasher-update-bytevector! h1 (bytevector 1 2 3)) (hasher-update-bytevector! h2 (bytevector 1 2 3))
       (hasher-update-flvector! h1 (flvector 1.1 2.2 3.3)) (hasher-update-flvector! h2 (flvector 1.1 2.2 3.3))

       (not (= (hasher-finalize! h1) (hasher-finalize! h2)))
       )

     )


(mat call-with-hasher

     (not (= (call-with-hasher 'xxhash32
                               (lambda (h1)
                                 (assert (hasher? h1))
                                 (hasher-update-fixnum! h1 1)
                                 (hasher-update-flonum! h1 1.5)
                                 (hasher-update-ratnum! h1 1/2)
                                 (hasher-update-cflonum! h1 1.5+2.5i)
                                 (hasher-update-bool! h1 #f)
                                 (hasher-update-char! h1 #\A)
                                 (hasher-update-string! h1 "hello")
                                 (hasher-update-fxvector! h1 (fxvector 1 2 3))
                                 (hasher-update-bytevector! h1 (bytevector 1 2 3))
                                 (hasher-update-flvector! h1 (flvector 1.1 2.2 3.3))))
             (call-with-hasher 'xxhash32 42
                               (lambda (h1)
                                 (assert (hasher? h1))
                                 (hasher-update-fixnum! h1 1)
                                 (hasher-update-flonum! h1 1.5)
                                 (hasher-update-ratnum! h1 1/2)
                                 (hasher-update-cflonum! h1 1.5+2.5i)
                                 (hasher-update-bool! h1 #f)
                                 (hasher-update-char! h1 #\A)
                                 (hasher-update-string! h1 "hello")
                                 (hasher-update-fxvector! h1 (fxvector 1 2 3))
                                 (hasher-update-bytevector! h1 (bytevector 1 2 3))
                                 (hasher-update-flvector! h1 (flvector 1.1 2.2 3.3))))))

     (not (= (call-with-hasher 'xxhash64
                               (lambda (h1)
                                 (assert (hasher? h1))
                                 (hasher-update-fixnum! h1 1)
                                 (hasher-update-flonum! h1 1.5)
                                 (hasher-update-ratnum! h1 1/2)
                                 (hasher-update-cflonum! h1 1.5+2.5i)
                                 (hasher-update-bool! h1 #f)
                                 (hasher-update-char! h1 #\A)
                                 (hasher-update-string! h1 "hello")
                                 (hasher-update-fxvector! h1 (fxvector 1 2 3))
                                 (hasher-update-bytevector! h1 (bytevector 1 2 3))
                                 (hasher-update-flvector! h1 (flvector 1.1 2.2 3.3))))
             (call-with-hasher 'xxhash64 42
                               (lambda (h1)
                                 (assert (hasher? h1))
                                 (hasher-update-fixnum! h1 1)
                                 (hasher-update-flonum! h1 1.5)
                                 (hasher-update-ratnum! h1 1/2)
                                 (hasher-update-cflonum! h1 1.5+2.5i)
                                 (hasher-update-bool! h1 #f)
                                 (hasher-update-char! h1 #\A)
                                 (hasher-update-string! h1 "hello")
                                 (hasher-update-fxvector! h1 (fxvector 1 2 3))
                                 (hasher-update-bytevector! h1 (bytevector 1 2 3))
                                 (hasher-update-flvector! h1 (flvector 1.1 2.2 3.3))))))

     (not (= (call-with-hasher 'xxhash3-64
                               (lambda (h1)
                                 (assert (hasher? h1))
                                 (hasher-update-fixnum! h1 1)
                                 (hasher-update-flonum! h1 1.5)
                                 (hasher-update-ratnum! h1 1/2)
                                 (hasher-update-cflonum! h1 1.5+2.5i)
                                 (hasher-update-bool! h1 #f)
                                 (hasher-update-char! h1 #\A)
                                 (hasher-update-string! h1 "hello")
                                 (hasher-update-fxvector! h1 (fxvector 1 2 3))
                                 (hasher-update-bytevector! h1 (bytevector 1 2 3))
                                 (hasher-update-flvector! h1 (flvector 1.1 2.2 3.3))))
             (call-with-hasher 'xxhash3-64 42
                               (lambda (h1)
                                 (assert (hasher? h1))
                                 (hasher-update-fixnum! h1 1)
                                 (hasher-update-flonum! h1 1.5)
                                 (hasher-update-ratnum! h1 1/2)
                                 (hasher-update-cflonum! h1 1.5+2.5i)
                                 (hasher-update-bool! h1 #f)
                                 (hasher-update-char! h1 #\A)
                                 (hasher-update-string! h1 "hello")
                                 (hasher-update-fxvector! h1 (fxvector 1 2 3))
                                 (hasher-update-bytevector! h1 (bytevector 1 2 3))
                                 (hasher-update-flvector! h1 (flvector 1.1 2.2 3.3))))))

     )
