(import (chezpp))
(load "net-lws-fixture.ss")
(mat net-http2-live-multiplexed-stress
 (call-with-h2-fixture 8 (lambda (port command)
  (let ([client (http-open)] [ok 0])
   (dynamic-wind void (lambda ()
    (http-client-version-set! client 'h2) (http-set-timeout! client 10000)
    (do ([round 0 (fx1+ round)]) ((fx= round 2))
     (for-each (lambda (path expected)
      (let ([r (http-get client (format "http://127.0.0.1:~a~a" port path))])
       (when (and (= 200 (http-response-status r)) (eq? 'h2 (http-response-version r))
                  (= expected (bytevector-length (http-response-body r)))) (set! ok (fx1+ ok)))))
      '("/" "/" "/large" "/") '(10 10 262144 10))) (= ok 8))
   (lambda () (http-close client)))))))
