(library (chezpp parser wasm opcodes)
  (export wasm-opcode-descriptor? wasm-opcode-mnemonic wasm-opcode-prefix
          wasm-opcode-code wasm-opcode-immediate-shape wasm-opcode-structured-kind
          wasm-core-3-opcodes wasm-opcode-by-binary wasm-opcode-by-mnemonic)
  (import (chezpp chez)
          (chezpp utils))

  (define-record-type ($wasm-opcode-descriptor make-wasm-opcode-descriptor
                                             $wasm-opcode-descriptor?)
    (fields (immutable mnemonic $wasm-opcode-mnemonic)
            (immutable prefix $wasm-opcode-prefix)
            (immutable code $wasm-opcode-code)
            (immutable immediate-shape $wasm-opcode-immediate-shape)
            (immutable structured-kind $wasm-opcode-structured-kind)))

  (define wasm-opcode-prefix?
    (lambda (value)
      (or (not value)
          (and (fixnum? value) (fx<= 0 value) (fx<= value #xff)))))

  (define wasm-opcode-code?
    (lambda (value)
      (and (natural? value) (<= value #xffffffff))))

  #|proc:wasm-opcode-descriptor?
  Returns whether `object` is a WebAssembly opcode descriptor. `object` is tested.
  |#
  (define wasm-opcode-descriptor?
    (lambda (object)
      (pcheck () ($wasm-opcode-descriptor? object))))

  #|proc:wasm-opcode-mnemonic
  Returns the canonical mnemonic of `descriptor`. `descriptor` is an opcode descriptor.
  |#
  (define wasm-opcode-mnemonic
    (lambda (descriptor)
      (pcheck ([$wasm-opcode-descriptor? descriptor])
              ($wasm-opcode-mnemonic descriptor))))

  #|proc:wasm-opcode-prefix
  Returns the prefix byte of `descriptor`, or `#f`. `descriptor` is an opcode descriptor.
  |#
  (define wasm-opcode-prefix
    (lambda (descriptor)
      (pcheck ([$wasm-opcode-descriptor? descriptor])
              ($wasm-opcode-prefix descriptor))))

  #|proc:wasm-opcode-code
  Returns the opcode or subopcode of `descriptor`. `descriptor` is an opcode descriptor.
  |#
  (define wasm-opcode-code
    (lambda (descriptor)
      (pcheck ([$wasm-opcode-descriptor? descriptor])
              ($wasm-opcode-code descriptor))))

  #|proc:wasm-opcode-immediate-shape
  Returns the immediate shape of `descriptor`. `descriptor` is an opcode descriptor.
  |#
  (define wasm-opcode-immediate-shape
    (lambda (descriptor)
      (pcheck ([$wasm-opcode-descriptor? descriptor])
              ($wasm-opcode-immediate-shape descriptor))))

  #|proc:wasm-opcode-structured-kind
  Returns the structured kind of `descriptor`, or `#f`. `descriptor` is an opcode descriptor.
  |#
  (define wasm-opcode-structured-kind
    (lambda (descriptor)
      (pcheck ([$wasm-opcode-descriptor? descriptor])
              ($wasm-opcode-structured-kind descriptor))))

  ;; The final Core 3.0 instruction index has 496 distinct WAT mnemonics.
  ;; `select` uses its typed encoding here because it represents the general WAT syntax.
  ;; `type-data` and `type-element` normalize to vectors in their binary operand order.
  ;; `memory-data` normalizes `(dataidx memidx)` to `(memidx dataidx)`.
  ;; `table-element` normalizes `(elemidx tableidx)` to `(tableidx elemidx)`.
  ;; The two heap-type shapes construct non-nullable or nullable reference-type records.
  (define wasm-core-3-opcodes
    (vector->immutable-vector
     (vector
     ;; parametric
     (make-wasm-opcode-descriptor 'unreachable #f 0 'none #f)
     (make-wasm-opcode-descriptor 'nop #f 1 'none #f)
     ;; control/exceptions/tail-call
     (make-wasm-opcode-descriptor 'block #f 2 'block-type 'block)
     (make-wasm-opcode-descriptor 'loop #f 3 'block-type 'loop)
     (make-wasm-opcode-descriptor 'if #f 4 'block-type 'if)
     (make-wasm-opcode-descriptor 'else #f 5 'none #f)
     (make-wasm-opcode-descriptor 'throw #f 8 'tag-index #f)
     (make-wasm-opcode-descriptor 'throw-ref #f 10 'none #f)
     (make-wasm-opcode-descriptor 'end #f 11 'none #f)
     (make-wasm-opcode-descriptor 'br #f 12 'label-index #f)
     (make-wasm-opcode-descriptor 'br-if #f 13 'label-index #f)
     (make-wasm-opcode-descriptor 'br-table #f 14 'label-vector #f)
     (make-wasm-opcode-descriptor 'return #f 15 'none #f)
     (make-wasm-opcode-descriptor 'call #f 16 'function-index #f)
     (make-wasm-opcode-descriptor 'call-indirect #f 17 'call-indirect #f)
     (make-wasm-opcode-descriptor 'return-call #f 18 'function-index #f)
     (make-wasm-opcode-descriptor 'return-call-indirect #f 19 'call-indirect #f)
     (make-wasm-opcode-descriptor 'call-ref #f 20 'type-index #f)
     (make-wasm-opcode-descriptor 'return-call-ref #f 21 'type-index #f)
     ;; parametric
     (make-wasm-opcode-descriptor 'drop #f 26 'none #f)
     (make-wasm-opcode-descriptor 'select #f 28 'select-types #f)
     ;; control/exceptions/tail-call
     (make-wasm-opcode-descriptor 'try-table #f 31 'try-table 'try-table)
     ;; variable
     (make-wasm-opcode-descriptor 'local.get #f 32 'local-index #f)
     (make-wasm-opcode-descriptor 'local.set #f 33 'local-index #f)
     (make-wasm-opcode-descriptor 'local.tee #f 34 'local-index #f)
     (make-wasm-opcode-descriptor 'global.get #f 35 'global-index #f)
     (make-wasm-opcode-descriptor 'global.set #f 36 'global-index #f)
     ;; table
     (make-wasm-opcode-descriptor 'table.get #f 37 'table-index #f)
     (make-wasm-opcode-descriptor 'table.set #f 38 'table-index #f)
     ;; memory
     (make-wasm-opcode-descriptor 'i32.load #f 40 'memory-argument #f)
     (make-wasm-opcode-descriptor 'i64.load #f 41 'memory-argument #f)
     (make-wasm-opcode-descriptor 'f32.load #f 42 'memory-argument #f)
     (make-wasm-opcode-descriptor 'f64.load #f 43 'memory-argument #f)
     (make-wasm-opcode-descriptor 'i32.load8-s #f 44 'memory-argument #f)
     (make-wasm-opcode-descriptor 'i32.load8-u #f 45 'memory-argument #f)
     (make-wasm-opcode-descriptor 'i32.load16-s #f 46 'memory-argument #f)
     (make-wasm-opcode-descriptor 'i32.load16-u #f 47 'memory-argument #f)
     (make-wasm-opcode-descriptor 'i64.load8-s #f 48 'memory-argument #f)
     (make-wasm-opcode-descriptor 'i64.load8-u #f 49 'memory-argument #f)
     (make-wasm-opcode-descriptor 'i64.load16-s #f 50 'memory-argument #f)
     (make-wasm-opcode-descriptor 'i64.load16-u #f 51 'memory-argument #f)
     (make-wasm-opcode-descriptor 'i64.load32-s #f 52 'memory-argument #f)
     (make-wasm-opcode-descriptor 'i64.load32-u #f 53 'memory-argument #f)
     (make-wasm-opcode-descriptor 'i32.store #f 54 'memory-argument #f)
     (make-wasm-opcode-descriptor 'i64.store #f 55 'memory-argument #f)
     (make-wasm-opcode-descriptor 'f32.store #f 56 'memory-argument #f)
     (make-wasm-opcode-descriptor 'f64.store #f 57 'memory-argument #f)
     (make-wasm-opcode-descriptor 'i32.store8 #f 58 'memory-argument #f)
     (make-wasm-opcode-descriptor 'i32.store16 #f 59 'memory-argument #f)
     (make-wasm-opcode-descriptor 'i64.store8 #f 60 'memory-argument #f)
     (make-wasm-opcode-descriptor 'i64.store16 #f 61 'memory-argument #f)
     (make-wasm-opcode-descriptor 'i64.store32 #f 62 'memory-argument #f)
     (make-wasm-opcode-descriptor 'memory.size #f 63 'memory-index #f)
     (make-wasm-opcode-descriptor 'memory.grow #f 64 'memory-index #f)
     ;; numeric
     (make-wasm-opcode-descriptor 'i32.const #f 65 'i32 #f)
     (make-wasm-opcode-descriptor 'i64.const #f 66 'i64 #f)
     (make-wasm-opcode-descriptor 'f32.const #f 67 'f32 #f)
     (make-wasm-opcode-descriptor 'f64.const #f 68 'f64 #f)
     (make-wasm-opcode-descriptor 'i32.eqz #f 69 'none #f)
     (make-wasm-opcode-descriptor 'i32.eq #f 70 'none #f)
     (make-wasm-opcode-descriptor 'i32.ne #f 71 'none #f)
     (make-wasm-opcode-descriptor 'i32.lt-s #f 72 'none #f)
     (make-wasm-opcode-descriptor 'i32.lt-u #f 73 'none #f)
     (make-wasm-opcode-descriptor 'i32.gt-s #f 74 'none #f)
     (make-wasm-opcode-descriptor 'i32.gt-u #f 75 'none #f)
     (make-wasm-opcode-descriptor 'i32.le-s #f 76 'none #f)
     (make-wasm-opcode-descriptor 'i32.le-u #f 77 'none #f)
     (make-wasm-opcode-descriptor 'i32.ge-s #f 78 'none #f)
     (make-wasm-opcode-descriptor 'i32.ge-u #f 79 'none #f)
     (make-wasm-opcode-descriptor 'i64.eqz #f 80 'none #f)
     (make-wasm-opcode-descriptor 'i64.eq #f 81 'none #f)
     (make-wasm-opcode-descriptor 'i64.ne #f 82 'none #f)
     (make-wasm-opcode-descriptor 'i64.lt-s #f 83 'none #f)
     (make-wasm-opcode-descriptor 'i64.lt-u #f 84 'none #f)
     (make-wasm-opcode-descriptor 'i64.gt-s #f 85 'none #f)
     (make-wasm-opcode-descriptor 'i64.gt-u #f 86 'none #f)
     (make-wasm-opcode-descriptor 'i64.le-s #f 87 'none #f)
     (make-wasm-opcode-descriptor 'i64.le-u #f 88 'none #f)
     (make-wasm-opcode-descriptor 'i64.ge-s #f 89 'none #f)
     (make-wasm-opcode-descriptor 'i64.ge-u #f 90 'none #f)
     (make-wasm-opcode-descriptor 'f32.eq #f 91 'none #f)
     (make-wasm-opcode-descriptor 'f32.ne #f 92 'none #f)
     (make-wasm-opcode-descriptor 'f32.lt #f 93 'none #f)
     (make-wasm-opcode-descriptor 'f32.gt #f 94 'none #f)
     (make-wasm-opcode-descriptor 'f32.le #f 95 'none #f)
     (make-wasm-opcode-descriptor 'f32.ge #f 96 'none #f)
     (make-wasm-opcode-descriptor 'f64.eq #f 97 'none #f)
     (make-wasm-opcode-descriptor 'f64.ne #f 98 'none #f)
     (make-wasm-opcode-descriptor 'f64.lt #f 99 'none #f)
     (make-wasm-opcode-descriptor 'f64.gt #f 100 'none #f)
     (make-wasm-opcode-descriptor 'f64.le #f 101 'none #f)
     (make-wasm-opcode-descriptor 'f64.ge #f 102 'none #f)
     (make-wasm-opcode-descriptor 'i32.clz #f 103 'none #f)
     (make-wasm-opcode-descriptor 'i32.ctz #f 104 'none #f)
     (make-wasm-opcode-descriptor 'i32.popcnt #f 105 'none #f)
     (make-wasm-opcode-descriptor 'i32.add #f 106 'none #f)
     (make-wasm-opcode-descriptor 'i32.sub #f 107 'none #f)
     (make-wasm-opcode-descriptor 'i32.mul #f 108 'none #f)
     (make-wasm-opcode-descriptor 'i32.div-s #f 109 'none #f)
     (make-wasm-opcode-descriptor 'i32.div-u #f 110 'none #f)
     (make-wasm-opcode-descriptor 'i32.rem-s #f 111 'none #f)
     (make-wasm-opcode-descriptor 'i32.rem-u #f 112 'none #f)
     (make-wasm-opcode-descriptor 'i32.and #f 113 'none #f)
     (make-wasm-opcode-descriptor 'i32.or #f 114 'none #f)
     (make-wasm-opcode-descriptor 'i32.xor #f 115 'none #f)
     (make-wasm-opcode-descriptor 'i32.shl #f 116 'none #f)
     (make-wasm-opcode-descriptor 'i32.shr-s #f 117 'none #f)
     (make-wasm-opcode-descriptor 'i32.shr-u #f 118 'none #f)
     (make-wasm-opcode-descriptor 'i32.rotl #f 119 'none #f)
     (make-wasm-opcode-descriptor 'i32.rotr #f 120 'none #f)
     (make-wasm-opcode-descriptor 'i64.clz #f 121 'none #f)
     (make-wasm-opcode-descriptor 'i64.ctz #f 122 'none #f)
     (make-wasm-opcode-descriptor 'i64.popcnt #f 123 'none #f)
     (make-wasm-opcode-descriptor 'i64.add #f 124 'none #f)
     (make-wasm-opcode-descriptor 'i64.sub #f 125 'none #f)
     (make-wasm-opcode-descriptor 'i64.mul #f 126 'none #f)
     (make-wasm-opcode-descriptor 'i64.div-s #f 127 'none #f)
     (make-wasm-opcode-descriptor 'i64.div-u #f 128 'none #f)
     (make-wasm-opcode-descriptor 'i64.rem-s #f 129 'none #f)
     (make-wasm-opcode-descriptor 'i64.rem-u #f 130 'none #f)
     (make-wasm-opcode-descriptor 'i64.and #f 131 'none #f)
     (make-wasm-opcode-descriptor 'i64.or #f 132 'none #f)
     (make-wasm-opcode-descriptor 'i64.xor #f 133 'none #f)
     (make-wasm-opcode-descriptor 'i64.shl #f 134 'none #f)
     (make-wasm-opcode-descriptor 'i64.shr-s #f 135 'none #f)
     (make-wasm-opcode-descriptor 'i64.shr-u #f 136 'none #f)
     (make-wasm-opcode-descriptor 'i64.rotl #f 137 'none #f)
     (make-wasm-opcode-descriptor 'i64.rotr #f 138 'none #f)
     (make-wasm-opcode-descriptor 'f32.abs #f 139 'none #f)
     (make-wasm-opcode-descriptor 'f32.neg #f 140 'none #f)
     (make-wasm-opcode-descriptor 'f32.ceil #f 141 'none #f)
     (make-wasm-opcode-descriptor 'f32.floor #f 142 'none #f)
     (make-wasm-opcode-descriptor 'f32.trunc #f 143 'none #f)
     (make-wasm-opcode-descriptor 'f32.nearest #f 144 'none #f)
     (make-wasm-opcode-descriptor 'f32.sqrt #f 145 'none #f)
     (make-wasm-opcode-descriptor 'f32.add #f 146 'none #f)
     (make-wasm-opcode-descriptor 'f32.sub #f 147 'none #f)
     (make-wasm-opcode-descriptor 'f32.mul #f 148 'none #f)
     (make-wasm-opcode-descriptor 'f32.div #f 149 'none #f)
     (make-wasm-opcode-descriptor 'f32.min #f 150 'none #f)
     (make-wasm-opcode-descriptor 'f32.max #f 151 'none #f)
     (make-wasm-opcode-descriptor 'f32.copysign #f 152 'none #f)
     (make-wasm-opcode-descriptor 'f64.abs #f 153 'none #f)
     (make-wasm-opcode-descriptor 'f64.neg #f 154 'none #f)
     (make-wasm-opcode-descriptor 'f64.ceil #f 155 'none #f)
     (make-wasm-opcode-descriptor 'f64.floor #f 156 'none #f)
     (make-wasm-opcode-descriptor 'f64.trunc #f 157 'none #f)
     (make-wasm-opcode-descriptor 'f64.nearest #f 158 'none #f)
     (make-wasm-opcode-descriptor 'f64.sqrt #f 159 'none #f)
     (make-wasm-opcode-descriptor 'f64.add #f 160 'none #f)
     (make-wasm-opcode-descriptor 'f64.sub #f 161 'none #f)
     (make-wasm-opcode-descriptor 'f64.mul #f 162 'none #f)
     (make-wasm-opcode-descriptor 'f64.div #f 163 'none #f)
     (make-wasm-opcode-descriptor 'f64.min #f 164 'none #f)
     (make-wasm-opcode-descriptor 'f64.max #f 165 'none #f)
     (make-wasm-opcode-descriptor 'f64.copysign #f 166 'none #f)
     (make-wasm-opcode-descriptor 'i32.wrap-i64 #f 167 'none #f)
     (make-wasm-opcode-descriptor 'i32.trunc-f32-s #f 168 'none #f)
     (make-wasm-opcode-descriptor 'i32.trunc-f32-u #f 169 'none #f)
     (make-wasm-opcode-descriptor 'i32.trunc-f64-s #f 170 'none #f)
     (make-wasm-opcode-descriptor 'i32.trunc-f64-u #f 171 'none #f)
     (make-wasm-opcode-descriptor 'i64.extend-i32-s #f 172 'none #f)
     (make-wasm-opcode-descriptor 'i64.extend-i32-u #f 173 'none #f)
     (make-wasm-opcode-descriptor 'i64.trunc-f32-s #f 174 'none #f)
     (make-wasm-opcode-descriptor 'i64.trunc-f32-u #f 175 'none #f)
     (make-wasm-opcode-descriptor 'i64.trunc-f64-s #f 176 'none #f)
     (make-wasm-opcode-descriptor 'i64.trunc-f64-u #f 177 'none #f)
     (make-wasm-opcode-descriptor 'f32.convert-i32-s #f 178 'none #f)
     (make-wasm-opcode-descriptor 'f32.convert-i32-u #f 179 'none #f)
     (make-wasm-opcode-descriptor 'f32.convert-i64-s #f 180 'none #f)
     (make-wasm-opcode-descriptor 'f32.convert-i64-u #f 181 'none #f)
     (make-wasm-opcode-descriptor 'f32.demote-f64 #f 182 'none #f)
     (make-wasm-opcode-descriptor 'f64.convert-i32-s #f 183 'none #f)
     (make-wasm-opcode-descriptor 'f64.convert-i32-u #f 184 'none #f)
     (make-wasm-opcode-descriptor 'f64.convert-i64-s #f 185 'none #f)
     (make-wasm-opcode-descriptor 'f64.convert-i64-u #f 186 'none #f)
     (make-wasm-opcode-descriptor 'f64.promote-f32 #f 187 'none #f)
     (make-wasm-opcode-descriptor 'i32.reinterpret-f32 #f 188 'none #f)
     (make-wasm-opcode-descriptor 'i64.reinterpret-f64 #f 189 'none #f)
     (make-wasm-opcode-descriptor 'f32.reinterpret-i32 #f 190 'none #f)
     (make-wasm-opcode-descriptor 'f64.reinterpret-i64 #f 191 'none #f)
     (make-wasm-opcode-descriptor 'i32.extend8-s #f 192 'none #f)
     (make-wasm-opcode-descriptor 'i32.extend16-s #f 193 'none #f)
     (make-wasm-opcode-descriptor 'i64.extend8-s #f 194 'none #f)
     (make-wasm-opcode-descriptor 'i64.extend16-s #f 195 'none #f)
     (make-wasm-opcode-descriptor 'i64.extend32-s #f 196 'none #f)
     ;; reference
     (make-wasm-opcode-descriptor 'ref.null #f 208 'heap-type #f)
     (make-wasm-opcode-descriptor 'ref.is-null #f 209 'none #f)
     (make-wasm-opcode-descriptor 'ref.func #f 210 'function-index #f)
     (make-wasm-opcode-descriptor 'ref.eq #f 211 'none #f)
     (make-wasm-opcode-descriptor 'ref.as-non-null #f 212 'none #f)
     ;; control/exceptions/tail-call
     (make-wasm-opcode-descriptor 'br-on-null #f 213 'label-index #f)
     (make-wasm-opcode-descriptor 'br-on-non-null #f 214 'label-index #f)
     ;; aggregate/gc
     (make-wasm-opcode-descriptor 'struct.new 251 0 'type-index #f)
     (make-wasm-opcode-descriptor 'struct.new-default 251 1 'type-index #f)
     (make-wasm-opcode-descriptor 'struct.get 251 2 'struct-field #f)
     (make-wasm-opcode-descriptor 'struct.get-s 251 3 'struct-field #f)
     (make-wasm-opcode-descriptor 'struct.get-u 251 4 'struct-field #f)
     (make-wasm-opcode-descriptor 'struct.set 251 5 'struct-field #f)
     (make-wasm-opcode-descriptor 'array.new 251 6 'type-index #f)
     (make-wasm-opcode-descriptor 'array.new-default 251 7 'type-index #f)
     (make-wasm-opcode-descriptor 'array.new-fixed 251 8 'array-new-fixed #f)
     (make-wasm-opcode-descriptor 'array.new-data 251 9 'type-data #f)
     (make-wasm-opcode-descriptor 'array.new-elem 251 10 'type-element #f)
     (make-wasm-opcode-descriptor 'array.get 251 11 'type-index #f)
     (make-wasm-opcode-descriptor 'array.get-s 251 12 'type-index #f)
     (make-wasm-opcode-descriptor 'array.get-u 251 13 'type-index #f)
     (make-wasm-opcode-descriptor 'array.set 251 14 'type-index #f)
     (make-wasm-opcode-descriptor 'array.len 251 15 'none #f)
     (make-wasm-opcode-descriptor 'array.fill 251 16 'type-index #f)
     (make-wasm-opcode-descriptor 'array.copy 251 17 'array-copy #f)
     (make-wasm-opcode-descriptor 'array.init-data 251 18 'type-data #f)
     (make-wasm-opcode-descriptor 'array.init-elem 251 19 'type-element #f)
     ;; reference
     (make-wasm-opcode-descriptor 'ref.test 251 20 'heap-type-non-null #f)
     (make-wasm-opcode-descriptor 'ref.cast 251 22 'heap-type-non-null #f)
     ;; control/exceptions/tail-call
     (make-wasm-opcode-descriptor 'br-on-cast 251 24 'br-on-cast #f)
     (make-wasm-opcode-descriptor 'br-on-cast-fail 251 25 'br-on-cast #f)
     ;; reference
     (make-wasm-opcode-descriptor 'any.convert-extern 251 26 'none #f)
     (make-wasm-opcode-descriptor 'extern.convert-any 251 27 'none #f)
     (make-wasm-opcode-descriptor 'ref.i31 251 28 'none #f)
     ;; aggregate/gc
     (make-wasm-opcode-descriptor 'i31.get-s 251 29 'none #f)
     (make-wasm-opcode-descriptor 'i31.get-u 251 30 'none #f)
     ;; numeric
     (make-wasm-opcode-descriptor 'i32.trunc-sat-f32-s 252 0 'none #f)
     (make-wasm-opcode-descriptor 'i32.trunc-sat-f32-u 252 1 'none #f)
     (make-wasm-opcode-descriptor 'i32.trunc-sat-f64-s 252 2 'none #f)
     (make-wasm-opcode-descriptor 'i32.trunc-sat-f64-u 252 3 'none #f)
     (make-wasm-opcode-descriptor 'i64.trunc-sat-f32-s 252 4 'none #f)
     (make-wasm-opcode-descriptor 'i64.trunc-sat-f32-u 252 5 'none #f)
     (make-wasm-opcode-descriptor 'i64.trunc-sat-f64-s 252 6 'none #f)
     (make-wasm-opcode-descriptor 'i64.trunc-sat-f64-u 252 7 'none #f)
     ;; memory
     (make-wasm-opcode-descriptor 'memory.init 252 8 'memory-data #f)
     (make-wasm-opcode-descriptor 'data.drop 252 9 'data-index #f)
     (make-wasm-opcode-descriptor 'memory.copy 252 10 'memory-pair #f)
     (make-wasm-opcode-descriptor 'memory.fill 252 11 'memory-index #f)
     ;; table
     (make-wasm-opcode-descriptor 'table.init 252 12 'table-element #f)
     (make-wasm-opcode-descriptor 'elem.drop 252 13 'element-index #f)
     (make-wasm-opcode-descriptor 'table.copy 252 14 'table-pair #f)
     (make-wasm-opcode-descriptor 'table.grow 252 15 'table-index #f)
     (make-wasm-opcode-descriptor 'table.size 252 16 'table-index #f)
     (make-wasm-opcode-descriptor 'table.fill 252 17 'table-index #f)
     ;; memory
     (make-wasm-opcode-descriptor 'v128.load 253 0 'memory-argument #f)
     (make-wasm-opcode-descriptor 'v128.load8x8-s 253 1 'memory-argument #f)
     (make-wasm-opcode-descriptor 'v128.load8x8-u 253 2 'memory-argument #f)
     (make-wasm-opcode-descriptor 'v128.load16x4-s 253 3 'memory-argument #f)
     (make-wasm-opcode-descriptor 'v128.load16x4-u 253 4 'memory-argument #f)
     (make-wasm-opcode-descriptor 'v128.load32x2-s 253 5 'memory-argument #f)
     (make-wasm-opcode-descriptor 'v128.load32x2-u 253 6 'memory-argument #f)
     (make-wasm-opcode-descriptor 'v128.load8-splat 253 7 'memory-argument #f)
     (make-wasm-opcode-descriptor 'v128.load16-splat 253 8 'memory-argument #f)
     (make-wasm-opcode-descriptor 'v128.load32-splat 253 9 'memory-argument #f)
     (make-wasm-opcode-descriptor 'v128.load64-splat 253 10 'memory-argument #f)
     (make-wasm-opcode-descriptor 'v128.store 253 11 'memory-argument #f)
     ;; vector
     (make-wasm-opcode-descriptor 'v128.const 253 12 'vector-bytes #f)
     (make-wasm-opcode-descriptor 'i8x16.shuffle 253 13 'shuffle-bytes #f)
     (make-wasm-opcode-descriptor 'i8x16.swizzle 253 14 'none #f)
     (make-wasm-opcode-descriptor 'i8x16.splat 253 15 'none #f)
     (make-wasm-opcode-descriptor 'i16x8.splat 253 16 'none #f)
     (make-wasm-opcode-descriptor 'i32x4.splat 253 17 'none #f)
     (make-wasm-opcode-descriptor 'i64x2.splat 253 18 'none #f)
     (make-wasm-opcode-descriptor 'f32x4.splat 253 19 'none #f)
     (make-wasm-opcode-descriptor 'f64x2.splat 253 20 'none #f)
     (make-wasm-opcode-descriptor 'i8x16.extract-lane-s 253 21 'lane-index #f)
     (make-wasm-opcode-descriptor 'i8x16.extract-lane-u 253 22 'lane-index #f)
     (make-wasm-opcode-descriptor 'i8x16.replace-lane 253 23 'lane-index #f)
     (make-wasm-opcode-descriptor 'i16x8.extract-lane-s 253 24 'lane-index #f)
     (make-wasm-opcode-descriptor 'i16x8.extract-lane-u 253 25 'lane-index #f)
     (make-wasm-opcode-descriptor 'i16x8.replace-lane 253 26 'lane-index #f)
     (make-wasm-opcode-descriptor 'i32x4.extract-lane 253 27 'lane-index #f)
     (make-wasm-opcode-descriptor 'i32x4.replace-lane 253 28 'lane-index #f)
     (make-wasm-opcode-descriptor 'i64x2.extract-lane 253 29 'lane-index #f)
     (make-wasm-opcode-descriptor 'i64x2.replace-lane 253 30 'lane-index #f)
     (make-wasm-opcode-descriptor 'f32x4.extract-lane 253 31 'lane-index #f)
     (make-wasm-opcode-descriptor 'f32x4.replace-lane 253 32 'lane-index #f)
     (make-wasm-opcode-descriptor 'f64x2.extract-lane 253 33 'lane-index #f)
     (make-wasm-opcode-descriptor 'f64x2.replace-lane 253 34 'lane-index #f)
     (make-wasm-opcode-descriptor 'i8x16.eq 253 35 'none #f)
     (make-wasm-opcode-descriptor 'i8x16.ne 253 36 'none #f)
     (make-wasm-opcode-descriptor 'i8x16.lt-s 253 37 'none #f)
     (make-wasm-opcode-descriptor 'i8x16.lt-u 253 38 'none #f)
     (make-wasm-opcode-descriptor 'i8x16.gt-s 253 39 'none #f)
     (make-wasm-opcode-descriptor 'i8x16.gt-u 253 40 'none #f)
     (make-wasm-opcode-descriptor 'i8x16.le-s 253 41 'none #f)
     (make-wasm-opcode-descriptor 'i8x16.le-u 253 42 'none #f)
     (make-wasm-opcode-descriptor 'i8x16.ge-s 253 43 'none #f)
     (make-wasm-opcode-descriptor 'i8x16.ge-u 253 44 'none #f)
     (make-wasm-opcode-descriptor 'i16x8.eq 253 45 'none #f)
     (make-wasm-opcode-descriptor 'i16x8.ne 253 46 'none #f)
     (make-wasm-opcode-descriptor 'i16x8.lt-s 253 47 'none #f)
     (make-wasm-opcode-descriptor 'i16x8.lt-u 253 48 'none #f)
     (make-wasm-opcode-descriptor 'i16x8.gt-s 253 49 'none #f)
     (make-wasm-opcode-descriptor 'i16x8.gt-u 253 50 'none #f)
     (make-wasm-opcode-descriptor 'i16x8.le-s 253 51 'none #f)
     (make-wasm-opcode-descriptor 'i16x8.le-u 253 52 'none #f)
     (make-wasm-opcode-descriptor 'i16x8.ge-s 253 53 'none #f)
     (make-wasm-opcode-descriptor 'i16x8.ge-u 253 54 'none #f)
     (make-wasm-opcode-descriptor 'i32x4.eq 253 55 'none #f)
     (make-wasm-opcode-descriptor 'i32x4.ne 253 56 'none #f)
     (make-wasm-opcode-descriptor 'i32x4.lt-s 253 57 'none #f)
     (make-wasm-opcode-descriptor 'i32x4.lt-u 253 58 'none #f)
     (make-wasm-opcode-descriptor 'i32x4.gt-s 253 59 'none #f)
     (make-wasm-opcode-descriptor 'i32x4.gt-u 253 60 'none #f)
     (make-wasm-opcode-descriptor 'i32x4.le-s 253 61 'none #f)
     (make-wasm-opcode-descriptor 'i32x4.le-u 253 62 'none #f)
     (make-wasm-opcode-descriptor 'i32x4.ge-s 253 63 'none #f)
     (make-wasm-opcode-descriptor 'i32x4.ge-u 253 64 'none #f)
     (make-wasm-opcode-descriptor 'f32x4.eq 253 65 'none #f)
     (make-wasm-opcode-descriptor 'f32x4.ne 253 66 'none #f)
     (make-wasm-opcode-descriptor 'f32x4.lt 253 67 'none #f)
     (make-wasm-opcode-descriptor 'f32x4.gt 253 68 'none #f)
     (make-wasm-opcode-descriptor 'f32x4.le 253 69 'none #f)
     (make-wasm-opcode-descriptor 'f32x4.ge 253 70 'none #f)
     (make-wasm-opcode-descriptor 'f64x2.eq 253 71 'none #f)
     (make-wasm-opcode-descriptor 'f64x2.ne 253 72 'none #f)
     (make-wasm-opcode-descriptor 'f64x2.lt 253 73 'none #f)
     (make-wasm-opcode-descriptor 'f64x2.gt 253 74 'none #f)
     (make-wasm-opcode-descriptor 'f64x2.le 253 75 'none #f)
     (make-wasm-opcode-descriptor 'f64x2.ge 253 76 'none #f)
     (make-wasm-opcode-descriptor 'v128.not 253 77 'none #f)
     (make-wasm-opcode-descriptor 'v128.and 253 78 'none #f)
     (make-wasm-opcode-descriptor 'v128.andnot 253 79 'none #f)
     (make-wasm-opcode-descriptor 'v128.or 253 80 'none #f)
     (make-wasm-opcode-descriptor 'v128.xor 253 81 'none #f)
     (make-wasm-opcode-descriptor 'v128.bitselect 253 82 'none #f)
     (make-wasm-opcode-descriptor 'v128.any-true 253 83 'none #f)
     ;; memory
     (make-wasm-opcode-descriptor 'v128.load8-lane 253 84 'memory-argument-lane #f)
     (make-wasm-opcode-descriptor 'v128.load16-lane 253 85 'memory-argument-lane #f)
     (make-wasm-opcode-descriptor 'v128.load32-lane 253 86 'memory-argument-lane #f)
     (make-wasm-opcode-descriptor 'v128.load64-lane 253 87 'memory-argument-lane #f)
     (make-wasm-opcode-descriptor 'v128.store8-lane 253 88 'memory-argument-lane #f)
     (make-wasm-opcode-descriptor 'v128.store16-lane 253 89 'memory-argument-lane #f)
     (make-wasm-opcode-descriptor 'v128.store32-lane 253 90 'memory-argument-lane #f)
     (make-wasm-opcode-descriptor 'v128.store64-lane 253 91 'memory-argument-lane #f)
     (make-wasm-opcode-descriptor 'v128.load32-zero 253 92 'memory-argument #f)
     (make-wasm-opcode-descriptor 'v128.load64-zero 253 93 'memory-argument #f)
     ;; vector
     (make-wasm-opcode-descriptor 'f32x4.demote-f64x2-zero 253 94 'none #f)
     (make-wasm-opcode-descriptor 'f64x2.promote-low-f32x4 253 95 'none #f)
     (make-wasm-opcode-descriptor 'i8x16.abs 253 96 'none #f)
     (make-wasm-opcode-descriptor 'i8x16.neg 253 97 'none #f)
     (make-wasm-opcode-descriptor 'i8x16.popcnt 253 98 'none #f)
     (make-wasm-opcode-descriptor 'i8x16.all-true 253 99 'none #f)
     (make-wasm-opcode-descriptor 'i8x16.bitmask 253 100 'none #f)
     (make-wasm-opcode-descriptor 'i8x16.narrow-i16x8-s 253 101 'none #f)
     (make-wasm-opcode-descriptor 'i8x16.narrow-i16x8-u 253 102 'none #f)
     (make-wasm-opcode-descriptor 'f32x4.ceil 253 103 'none #f)
     (make-wasm-opcode-descriptor 'f32x4.floor 253 104 'none #f)
     (make-wasm-opcode-descriptor 'f32x4.trunc 253 105 'none #f)
     (make-wasm-opcode-descriptor 'f32x4.nearest 253 106 'none #f)
     (make-wasm-opcode-descriptor 'i8x16.shl 253 107 'none #f)
     (make-wasm-opcode-descriptor 'i8x16.shr-s 253 108 'none #f)
     (make-wasm-opcode-descriptor 'i8x16.shr-u 253 109 'none #f)
     (make-wasm-opcode-descriptor 'i8x16.add 253 110 'none #f)
     (make-wasm-opcode-descriptor 'i8x16.add-sat-s 253 111 'none #f)
     (make-wasm-opcode-descriptor 'i8x16.add-sat-u 253 112 'none #f)
     (make-wasm-opcode-descriptor 'i8x16.sub 253 113 'none #f)
     (make-wasm-opcode-descriptor 'i8x16.sub-sat-s 253 114 'none #f)
     (make-wasm-opcode-descriptor 'i8x16.sub-sat-u 253 115 'none #f)
     (make-wasm-opcode-descriptor 'f64x2.ceil 253 116 'none #f)
     (make-wasm-opcode-descriptor 'f64x2.floor 253 117 'none #f)
     (make-wasm-opcode-descriptor 'i8x16.min-s 253 118 'none #f)
     (make-wasm-opcode-descriptor 'i8x16.min-u 253 119 'none #f)
     (make-wasm-opcode-descriptor 'i8x16.max-s 253 120 'none #f)
     (make-wasm-opcode-descriptor 'i8x16.max-u 253 121 'none #f)
     (make-wasm-opcode-descriptor 'f64x2.trunc 253 122 'none #f)
     (make-wasm-opcode-descriptor 'i8x16.avgr-u 253 123 'none #f)
     (make-wasm-opcode-descriptor 'i16x8.extadd-pairwise-i8x16-s 253 124 'none #f)
     (make-wasm-opcode-descriptor 'i16x8.extadd-pairwise-i8x16-u 253 125 'none #f)
     (make-wasm-opcode-descriptor 'i32x4.extadd-pairwise-i16x8-s 253 126 'none #f)
     (make-wasm-opcode-descriptor 'i32x4.extadd-pairwise-i16x8-u 253 127 'none #f)
     (make-wasm-opcode-descriptor 'i16x8.abs 253 128 'none #f)
     (make-wasm-opcode-descriptor 'i16x8.neg 253 129 'none #f)
     (make-wasm-opcode-descriptor 'i16x8.q15mulr-sat-s 253 130 'none #f)
     (make-wasm-opcode-descriptor 'i16x8.all-true 253 131 'none #f)
     (make-wasm-opcode-descriptor 'i16x8.bitmask 253 132 'none #f)
     (make-wasm-opcode-descriptor 'i16x8.narrow-i32x4-s 253 133 'none #f)
     (make-wasm-opcode-descriptor 'i16x8.narrow-i32x4-u 253 134 'none #f)
     (make-wasm-opcode-descriptor 'i16x8.extend-low-i8x16-s 253 135 'none #f)
     (make-wasm-opcode-descriptor 'i16x8.extend-high-i8x16-s 253 136 'none #f)
     (make-wasm-opcode-descriptor 'i16x8.extend-low-i8x16-u 253 137 'none #f)
     (make-wasm-opcode-descriptor 'i16x8.extend-high-i8x16-u 253 138 'none #f)
     (make-wasm-opcode-descriptor 'i16x8.shl 253 139 'none #f)
     (make-wasm-opcode-descriptor 'i16x8.shr-s 253 140 'none #f)
     (make-wasm-opcode-descriptor 'i16x8.shr-u 253 141 'none #f)
     (make-wasm-opcode-descriptor 'i16x8.add 253 142 'none #f)
     (make-wasm-opcode-descriptor 'i16x8.add-sat-s 253 143 'none #f)
     (make-wasm-opcode-descriptor 'i16x8.add-sat-u 253 144 'none #f)
     (make-wasm-opcode-descriptor 'i16x8.sub 253 145 'none #f)
     (make-wasm-opcode-descriptor 'i16x8.sub-sat-s 253 146 'none #f)
     (make-wasm-opcode-descriptor 'i16x8.sub-sat-u 253 147 'none #f)
     (make-wasm-opcode-descriptor 'f64x2.nearest 253 148 'none #f)
     (make-wasm-opcode-descriptor 'i16x8.mul 253 149 'none #f)
     (make-wasm-opcode-descriptor 'i16x8.min-s 253 150 'none #f)
     (make-wasm-opcode-descriptor 'i16x8.min-u 253 151 'none #f)
     (make-wasm-opcode-descriptor 'i16x8.max-s 253 152 'none #f)
     (make-wasm-opcode-descriptor 'i16x8.max-u 253 153 'none #f)
     (make-wasm-opcode-descriptor 'i16x8.avgr-u 253 155 'none #f)
     (make-wasm-opcode-descriptor 'i16x8.extmul-low-i8x16-s 253 156 'none #f)
     (make-wasm-opcode-descriptor 'i16x8.extmul-high-i8x16-s 253 157 'none #f)
     (make-wasm-opcode-descriptor 'i16x8.extmul-low-i8x16-u 253 158 'none #f)
     (make-wasm-opcode-descriptor 'i16x8.extmul-high-i8x16-u 253 159 'none #f)
     (make-wasm-opcode-descriptor 'i32x4.abs 253 160 'none #f)
     (make-wasm-opcode-descriptor 'i32x4.neg 253 161 'none #f)
     (make-wasm-opcode-descriptor 'i32x4.all-true 253 163 'none #f)
     (make-wasm-opcode-descriptor 'i32x4.bitmask 253 164 'none #f)
     (make-wasm-opcode-descriptor 'i32x4.extend-low-i16x8-s 253 167 'none #f)
     (make-wasm-opcode-descriptor 'i32x4.extend-high-i16x8-s 253 168 'none #f)
     (make-wasm-opcode-descriptor 'i32x4.extend-low-i16x8-u 253 169 'none #f)
     (make-wasm-opcode-descriptor 'i32x4.extend-high-i16x8-u 253 170 'none #f)
     (make-wasm-opcode-descriptor 'i32x4.shl 253 171 'none #f)
     (make-wasm-opcode-descriptor 'i32x4.shr-s 253 172 'none #f)
     (make-wasm-opcode-descriptor 'i32x4.shr-u 253 173 'none #f)
     (make-wasm-opcode-descriptor 'i32x4.add 253 174 'none #f)
     (make-wasm-opcode-descriptor 'i32x4.sub 253 177 'none #f)
     (make-wasm-opcode-descriptor 'i32x4.mul 253 181 'none #f)
     (make-wasm-opcode-descriptor 'i32x4.min-s 253 182 'none #f)
     (make-wasm-opcode-descriptor 'i32x4.min-u 253 183 'none #f)
     (make-wasm-opcode-descriptor 'i32x4.max-s 253 184 'none #f)
     (make-wasm-opcode-descriptor 'i32x4.max-u 253 185 'none #f)
     (make-wasm-opcode-descriptor 'i32x4.dot-i16x8-s 253 186 'none #f)
     (make-wasm-opcode-descriptor 'i32x4.extmul-low-i16x8-s 253 188 'none #f)
     (make-wasm-opcode-descriptor 'i32x4.extmul-high-i16x8-s 253 189 'none #f)
     (make-wasm-opcode-descriptor 'i32x4.extmul-low-i16x8-u 253 190 'none #f)
     (make-wasm-opcode-descriptor 'i32x4.extmul-high-i16x8-u 253 191 'none #f)
     (make-wasm-opcode-descriptor 'i64x2.abs 253 192 'none #f)
     (make-wasm-opcode-descriptor 'i64x2.neg 253 193 'none #f)
     (make-wasm-opcode-descriptor 'i64x2.all-true 253 195 'none #f)
     (make-wasm-opcode-descriptor 'i64x2.bitmask 253 196 'none #f)
     (make-wasm-opcode-descriptor 'i64x2.extend-low-i32x4-s 253 199 'none #f)
     (make-wasm-opcode-descriptor 'i64x2.extend-high-i32x4-s 253 200 'none #f)
     (make-wasm-opcode-descriptor 'i64x2.extend-low-i32x4-u 253 201 'none #f)
     (make-wasm-opcode-descriptor 'i64x2.extend-high-i32x4-u 253 202 'none #f)
     (make-wasm-opcode-descriptor 'i64x2.shl 253 203 'none #f)
     (make-wasm-opcode-descriptor 'i64x2.shr-s 253 204 'none #f)
     (make-wasm-opcode-descriptor 'i64x2.shr-u 253 205 'none #f)
     (make-wasm-opcode-descriptor 'i64x2.add 253 206 'none #f)
     (make-wasm-opcode-descriptor 'i64x2.sub 253 209 'none #f)
     (make-wasm-opcode-descriptor 'i64x2.mul 253 213 'none #f)
     (make-wasm-opcode-descriptor 'i64x2.eq 253 214 'none #f)
     (make-wasm-opcode-descriptor 'i64x2.ne 253 215 'none #f)
     (make-wasm-opcode-descriptor 'i64x2.lt-s 253 216 'none #f)
     (make-wasm-opcode-descriptor 'i64x2.gt-s 253 217 'none #f)
     (make-wasm-opcode-descriptor 'i64x2.le-s 253 218 'none #f)
     (make-wasm-opcode-descriptor 'i64x2.ge-s 253 219 'none #f)
     (make-wasm-opcode-descriptor 'i64x2.extmul-low-i32x4-s 253 220 'none #f)
     (make-wasm-opcode-descriptor 'i64x2.extmul-high-i32x4-s 253 221 'none #f)
     (make-wasm-opcode-descriptor 'i64x2.extmul-low-i32x4-u 253 222 'none #f)
     (make-wasm-opcode-descriptor 'i64x2.extmul-high-i32x4-u 253 223 'none #f)
     (make-wasm-opcode-descriptor 'f32x4.abs 253 224 'none #f)
     (make-wasm-opcode-descriptor 'f32x4.neg 253 225 'none #f)
     (make-wasm-opcode-descriptor 'f32x4.sqrt 253 227 'none #f)
     (make-wasm-opcode-descriptor 'f32x4.add 253 228 'none #f)
     (make-wasm-opcode-descriptor 'f32x4.sub 253 229 'none #f)
     (make-wasm-opcode-descriptor 'f32x4.mul 253 230 'none #f)
     (make-wasm-opcode-descriptor 'f32x4.div 253 231 'none #f)
     (make-wasm-opcode-descriptor 'f32x4.min 253 232 'none #f)
     (make-wasm-opcode-descriptor 'f32x4.max 253 233 'none #f)
     (make-wasm-opcode-descriptor 'f32x4.pmin 253 234 'none #f)
     (make-wasm-opcode-descriptor 'f32x4.pmax 253 235 'none #f)
     (make-wasm-opcode-descriptor 'f64x2.abs 253 236 'none #f)
     (make-wasm-opcode-descriptor 'f64x2.neg 253 237 'none #f)
     (make-wasm-opcode-descriptor 'f64x2.sqrt 253 239 'none #f)
     (make-wasm-opcode-descriptor 'f64x2.add 253 240 'none #f)
     (make-wasm-opcode-descriptor 'f64x2.sub 253 241 'none #f)
     (make-wasm-opcode-descriptor 'f64x2.mul 253 242 'none #f)
     (make-wasm-opcode-descriptor 'f64x2.div 253 243 'none #f)
     (make-wasm-opcode-descriptor 'f64x2.min 253 244 'none #f)
     (make-wasm-opcode-descriptor 'f64x2.max 253 245 'none #f)
     (make-wasm-opcode-descriptor 'f64x2.pmin 253 246 'none #f)
     (make-wasm-opcode-descriptor 'f64x2.pmax 253 247 'none #f)
     (make-wasm-opcode-descriptor 'i32x4.trunc-sat-f32x4-s 253 248 'none #f)
     (make-wasm-opcode-descriptor 'i32x4.trunc-sat-f32x4-u 253 249 'none #f)
     (make-wasm-opcode-descriptor 'f32x4.convert-i32x4-s 253 250 'none #f)
     (make-wasm-opcode-descriptor 'f32x4.convert-i32x4-u 253 251 'none #f)
     (make-wasm-opcode-descriptor 'i32x4.trunc-sat-f64x2-s-zero 253 252 'none #f)
     (make-wasm-opcode-descriptor 'i32x4.trunc-sat-f64x2-u-zero 253 253 'none #f)
     (make-wasm-opcode-descriptor 'f64x2.convert-low-i32x4-s 253 254 'none #f)
     (make-wasm-opcode-descriptor 'f64x2.convert-low-i32x4-u 253 255 'none #f)
     ;; relaxed-simd
     (make-wasm-opcode-descriptor 'i8x16.relaxed-swizzle 253 256 'none #f)
     (make-wasm-opcode-descriptor 'i32x4.relaxed-trunc-f32x4-s 253 257 'none #f)
     (make-wasm-opcode-descriptor 'i32x4.relaxed-trunc-f32x4-u 253 258 'none #f)
     (make-wasm-opcode-descriptor 'i32x4.relaxed-trunc-f64x2-s-zero 253 259 'none #f)
     (make-wasm-opcode-descriptor 'i32x4.relaxed-trunc-f64x2-u-zero 253 260 'none #f)
     (make-wasm-opcode-descriptor 'f32x4.relaxed-madd 253 261 'none #f)
     (make-wasm-opcode-descriptor 'f32x4.relaxed-nmadd 253 262 'none #f)
     (make-wasm-opcode-descriptor 'f64x2.relaxed-madd 253 263 'none #f)
     (make-wasm-opcode-descriptor 'f64x2.relaxed-nmadd 253 264 'none #f)
     (make-wasm-opcode-descriptor 'i8x16.relaxed-laneselect 253 265 'none #f)
     (make-wasm-opcode-descriptor 'i16x8.relaxed-laneselect 253 266 'none #f)
     (make-wasm-opcode-descriptor 'i32x4.relaxed-laneselect 253 267 'none #f)
     (make-wasm-opcode-descriptor 'i64x2.relaxed-laneselect 253 268 'none #f)
     (make-wasm-opcode-descriptor 'f32x4.relaxed-min 253 269 'none #f)
     (make-wasm-opcode-descriptor 'f32x4.relaxed-max 253 270 'none #f)
     (make-wasm-opcode-descriptor 'f64x2.relaxed-min 253 271 'none #f)
     (make-wasm-opcode-descriptor 'f64x2.relaxed-max 253 272 'none #f)
     (make-wasm-opcode-descriptor 'i16x8.relaxed-q15mulr-s 253 273 'none #f)
     (make-wasm-opcode-descriptor 'i16x8.relaxed-dot-i8x16-i7x16-s 253 274 'none #f)
     (make-wasm-opcode-descriptor 'i32x4.relaxed-dot-i8x16-i7x16-add-s 253 275 'none #f))))

  ;; These final binary encodings share WAT mnemonics with canonical rows above. Keeping exact
  ;; descriptors here lets binary decoding recover the encoding-specific immediate shape while
  ;; mnemonic lookup remains deterministic. A binary result therefore need not be in the public
  ;; canonical vector.
  (define wasm-core-3-binary-variants
    (vector->immutable-vector
     (vector
      (make-wasm-opcode-descriptor 'select #f #x1b 'none #f)
      (make-wasm-opcode-descriptor 'ref.test #xfb 21 'heap-type-nullable #f)
      (make-wasm-opcode-descriptor 'ref.cast #xfb 23 'heap-type-nullable #f))))

  (define opcode-binary-key
    (lambda (prefix code)
      (+ code (ash (if prefix (+ prefix 1) 0) 32))))

  (define add-binary-descriptor!
    (lambda (table descriptor)
      (let ([key (opcode-binary-key ($wasm-opcode-prefix descriptor)
                                    ($wasm-opcode-code descriptor))])
        (when (hashtable-ref table key #f)
          (assertion-violation
           'wasm-core-3-opcodes "duplicate binary opcode"
           (vector ($wasm-opcode-prefix descriptor) ($wasm-opcode-code descriptor))))
        (hashtable-set! table key descriptor))))

  (define add-canonical-descriptor!
    (lambda (binary-table mnemonic-table descriptor)
      (let ([mnemonic ($wasm-opcode-mnemonic descriptor)])
        (when (hashtable-ref mnemonic-table mnemonic #f)
          (assertion-violation 'wasm-core-3-opcodes "duplicate mnemonic" mnemonic))
        (add-binary-descriptor! binary-table descriptor)
        (hashtable-set! mnemonic-table mnemonic descriptor))))

  (define build-opcode-tables
    (lambda ()
      (let ([binary-table (make-eqv-hashtable)]
            [mnemonic-table (make-eq-hashtable)])
        (let loop ([index 0])
          (unless (fx= index (vector-length wasm-core-3-opcodes))
            (add-canonical-descriptor!
             binary-table mnemonic-table (vector-ref wasm-core-3-opcodes index))
            (loop (fx1+ index))))
        (let loop ([index 0])
          (unless (fx= index (vector-length wasm-core-3-binary-variants))
            (add-binary-descriptor!
             binary-table (vector-ref wasm-core-3-binary-variants index))
            (loop (fx1+ index))))
        (values (hashtable-copy binary-table #f)
                (hashtable-copy mnemonic-table #f)))))

  (define-values (wasm-opcode-binary-table wasm-opcode-mnemonic-table)
    (build-opcode-tables))

  #|proc:wasm-opcode-by-binary
  Returns the exact binary descriptor for `prefix` and `code`, or `#f`. `prefix` is `#f` or a
  prefix byte, and `code` is a u32 one-byte opcode or prefixed subopcode. A binary variant result
  may not be a member of `wasm-core-3-opcodes`; mnemonic lookup always returns its canonical row.
  |#
  (define wasm-opcode-by-binary
    (lambda (prefix code)
      (pcheck ([wasm-opcode-prefix? prefix] [wasm-opcode-code? code])
              (hashtable-ref wasm-opcode-binary-table
                             (opcode-binary-key prefix code) #f))))

  #|proc:wasm-opcode-by-mnemonic
  Returns the canonical descriptor for `mnemonic`, or `#f`. `mnemonic` is a symbol.
  |#
  (define wasm-opcode-by-mnemonic
    (lambda (mnemonic)
      (pcheck ([symbol? mnemonic])
              (hashtable-ref wasm-opcode-mnemonic-table mnemonic #f))))

  )
