#!/bin/sh
# Resolve optional dependencies with the same compiler and flags used by the build.
set -eu

if [ "${1-}" = header ]; then
    destination=$2
    shift 2
    temporary=$(mktemp "${destination}.tmp.XXXXXX")
    trap 'rm -f "$temporary"' EXIT HUP INT TERM
    {
        printf '%s\n' '/* Generated by Make; do not edit. */' \
            '#ifndef CHEZPP_BUILD_CONFIG_H' '#define CHEZPP_BUILD_CONFIG_H'
        for feature do
            printf '#define CHEZPP_WITH_%s %s\n' "${feature%=*}" "${feature#*=}"
        done
        printf '%s\n' '#endif'
    } > "$temporary"
    if ! cmp -s "$temporary" "$destination"; then
        mv -f "$temporary" "$destination"
    fi
    exit 0
fi

workspace=$(mktemp -d)
trap 'rm -rf "$workspace"' EXIT HUP INT TERM
configuration="$workspace/config.mk"
: > "$configuration"
# Escape values that are syntax in a generated Make include, preserving literal flags.
assignment() {
    printf '%s := ' "$1" >> "$configuration"
    printf '%s\n' "$2" | sed 's/\$/$$/g; s/#/\\#/g' >> "$configuration"
}

for name in CARES CURL GRPC IDN2 LIBSSH WEBSOCKETS ZLIB OPENSSL UUID XXHASH BLAKE3; do
    eval 'choice=${WITH_'"$name"'}'
    eval 'cflags=${'"$name"'_CFLAGS-}'
    eval 'libs=${'"$name"'_LIBS-}'
    eval 'cflags_supplied=${'"$name"'_CFLAGS_SUPPLIED}'
    eval 'libs_supplied=${'"$name"'_LIBS_SUPPLIED}'
    case "$name" in
        CARES) package=libcares; header=ares.h; symbol=ares_library_init ;;
        CURL) package=libcurl; header=curl/curl.h; symbol=curl_version_info ;;
        GRPC) package=grpc; header=grpc/grpc.h; symbol=grpc_init ;;
        IDN2) package=libidn2; header=idn2.h; symbol=idn2_check_version ;;
        LIBSSH) package=libssh; header=libssh/libssh.h; symbol=ssh_version ;;
        WEBSOCKETS) package=libwebsockets; header=libwebsockets.h; symbol=lws_get_library_version ;;
        ZLIB) package=zlib; header=zlib.h; symbol=zlibVersion ;;
        OPENSSL) package=openssl; header=openssl/ssl.h; symbol=OPENSSL_init_ssl ;;
        UUID) package=uuid; header=uuid/uuid.h; symbol=uuid_generate ;;
        XXHASH) package=libxxhash; header=xxhash.h; symbol=XXH32 ;;
        BLAKE3) package=libblake3; header=blake3.h; symbol=blake3_hasher_init ;;
    esac
    enabled=0
    if [ "$choice" != 0 ]; then
        usable=1
        if [ "$cflags_supplied" = 0 ] || [ "$libs_supplied" = 0 ]; then
            if ! $PKG_CONFIG --exists "$package" 2> "$workspace/error"; then
                usable=0
                if [ "$choice" = 1 ]; then
                    printf 'error: WITH_%s=1 requires <%s> and package %s; pkg-config failed.\n' \
                        "$name" "$header" "$package" >&2
                    printf 'Supply both %s_CFLAGS and %s_LIBS (empty values count as supplied).\n' \
                        "$name" "$name" >&2
                    cat "$workspace/error" >&2
                    exit 1
                fi
            else
                if [ "$cflags_supplied" = 0 ]; then
                    if ! cflags=$($PKG_CONFIG --cflags "$package" 2> "$workspace/error"); then usable=0; fi
                fi
                if [ "$libs_supplied" = 0 ]; then
                    if ! libs=$($PKG_CONFIG --libs "$package" 2> "$workspace/error"); then usable=0; fi
                fi
                if [ "$usable" = 0 ] && [ "$choice" = 1 ]; then
                    printf 'error: WITH_%s=1 could not obtain flags for <%s> from pkg-config.\n' \
                        "$name" "$header" >&2
                    cat "$workspace/error" >&2
                    exit 1
                fi
            fi
        fi
        if [ "$usable" = 1 ]; then
            # A live volatile address survives optimization even for pure/const APIs.
            printf '#include <%s>\n__typeof__(&%s) volatile chezpp_probe_symbol = &%s;\nint main(void) { return chezpp_probe_symbol == 0; }\n' \
                "$header" "$symbol" "$symbol" > "$workspace/probe.c"
            # Flag strings use ordinary shell quoting, just as in the Make compiler recipe.
            if eval "$CC $CPPFLAGS $CFLAGS $cflags \"\$workspace/probe.c\" $LDFLAGS $libs -o \"\$workspace/probe\"" \
                > "$workspace/error" 2>&1; then
                enabled=1
            elif [ "$choice" = 1 ]; then
                printf 'error: WITH_%s=1 failed to compile/link <%s> with resolved %s_CFLAGS/%s_LIBS.\n' \
                    "$name" "$header" "$name" "$name" >&2
                cat "$workspace/error" >&2
                exit 1
            fi
        fi
    fi
    assignment "RESOLVED_WITH_$name" "$enabled"
    if [ "$enabled" = 0 ]; then cflags=; libs=; fi
    assignment "RESOLVED_${name}_CFLAGS" "$cflags"
    assignment "RESOLVED_${name}_LIBS" "$libs"
done
# The caller includes this private file and deletes it immediately afterwards.
result=$(mktemp)
mv -f "$configuration" "$result"
printf '%s\n' "$result"
