(library (chezpp parser)
  (export)
  (import (chezpp chez)
          (chezpp parser wasm opcodes)
          (chezpp parser wasm validate)
          (chezpp parser wasm binary)
          (chezpp parser wasm binary values)
          (chezpp parser wasm binary types)
          (chezpp parser wasm binary instructions)
          (chezpp parser wasm text lexical)
          (chezpp parser wasm text types)
          (chezpp parser wasm text instructions)
          (chezpp parser wasm normalize)
          (chezpp parser wasm text)
          (chezpp parser wasm private))

  (export (import (except (chezpp parser combinator)
                          parser-call input-pos input-pos-set! input-len
                          save-input binary-input-data
                          bindigits->num octdigits->num digits->num hexdigits->num)

                  (chezpp parser csv)
                  (chezpp parser json5)
                  (chezpp parser xml)
                  (chezpp parser scheme)
                  (chezpp parser toml)
                  (chezpp parser elf)
                  (chezpp parser wasm)))
  )
